xmms/collection: fix `xmms_collection_get_pointer` prototype
Detected by `gcc-13` warning as:

    ../src/xmms/collection.c:862:1: warning: conflicting types for ‘xmms_collection_get_pointer’
      due to enum/integer mismatch; have ‘xmmsv_t *(xmms_coll_dag_t *, const gchar *, xmms_collection_namespace_id_t)’ {aka ‘struct xmmsv_St *(struct xmms_coll_dag_St *, const char *, xmms_collection_namespace_id_t)’} [-Wenum-int-mismatch]
      862 | xmms_collection_get_pointer (xmms_coll_dag_t *dag, const gchar *collname,
          | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from ../src/xmms/collection.c:29:
    ../src/includepriv/xmmspriv/xmms_collection.h:65:11: note: previous declaration of ‘xmms_collection_get_pointer’
      with type ‘xmmsv_t *(xmms_coll_dag_t *, const gchar *, guint)’ {aka ‘struct xmmsv_St *(struct xmms_coll_dag_St *, const char *, unsigned int)’}
       65 | xmmsv_t * xmms_collection_get_pointer (xmms_coll_dag_t *dag, const gchar *collname, guint namespace);
          |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~