avcodec: adapt to ffmpeg-7
ffmpeg-7 removed long deprecated API of accessing channels. As a result
`xmms2` fails the build now against `ffmpeg-7.0.2` as:

    ../src/plugins/avcodec/avcodec.c: In function ‘xmms_avcodec_init’:
    ../src/plugins/avcodec/avcodec.c:225:23: error: ‘AVCodecContext’ has no member named ‘channels’
      225 |         data->codecctx->channels = data->channels;
          |                       ^~

The change follows a trivial change of switching to new style similar to
upstream example update at:

    https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/f5ef91e02080316f50d606f5b0b03333bb627ed7