src/clients/lib/xmmsclient/xmmsclient.c: fix `-std=c23` build
gcc-15 switched to -std=c23 by default:

    https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212

Without the change the build fails as:

    ../src/clients/lib/xmmsclient/xmmsclient.c:225:55: error: incompatible types when returning type ‘_Bool’ but ‘char *’ was expected
      225 |         x_api_error_if (!c, "with a NULL connection", false);
          |                                                       ^~~~~