OTHER: wscript: make implicit function declarations an error in C code
Implicit function declarations can lead to hard to debug errors on 64-bit systems
(int is usually 32bit there, while arguments have all chances to be 64bit).

It also converts link-time failures to compile-time ones. Fresh example:

    $ LANG=C ./waf build
    Waf: Entering directory `/mnt/archive/work/dev/git/xmms2-devel/slyfox/_build_'
    [ 83/337] cc: src/clients/lib/xmmsclient/visualization/unixshm.c -> _build_/default/src/clients/lib/xmmsclient/visualization/unixshm_1.o
    [ 84/337] cc: src/clients/lib/xmmsclient-glib/xmmsclient-glib.c -> _build_/default/src/clients/lib/xmmsclient-glib/xmmsclient-glib_1.o
    ../src/clients/lib/xmmsclient/visualization/unixshm.c: In function 'decrement_client':
    ../src/clients/lib/xmmsclient/visualization/unixshm.c:102: error: implicit declaration of function 'semtimedop' [-Wimplicit-function-declaration]
    Waf: Leaving directory `/mnt/archive/work/dev/git/xmms2-devel/slyfox/_build_'
    Build failed
     -> task failed (err #1):
            {task: cc unixshm.c -> unixshm_1.o}

Patch also adds pretty-printer for warnings: -fdiagnostics-show-option
Warings are now seen with flags generating them:

    ../src/lib/xmmstypes/value.c:2385: warning: 'XMMSV_TYPE_UINT32_IS_DEPRECATED'
    is deprecated (declared at ../src/include/xmmsc/xmmsv.h:43) [-Wdeprecated-declarations]

    ../src/clients/lib/xmmsclient/bindata.c:36: warning: unused variable 'res' [-Wunused-variable]

    ../src/clients/lib/xmmsclient++/playlist.cpp:201: warning: 'xmmsc_result_t*
    xmmsc_playlist_insert_args(xmmsc_connection_t*, const char*, int, const char*, int, const char**)'
    is deprecated (declared at ../src/include/xmmsclient/xmmsclient.h:95) [-Wdeprecated-declarations]

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>