avcodec: restore ffmpeg-4 support
At least `xmm2` CI still uses older `ffmpeg` which caused build failre
as:

    ../src/plugins/avcodec/avcodec.c:225:18: error: no member named 'ch_layout' in 'struct AVCodecContext'
        data->codecctx->ch_layout.nb_channels = data->channels;
        ~~~~~~~~~~~~~~  ^

The change brings in compatibility macro to accomobate for rename.