src/clients/lib/xmmsclient/service/client.c: fix `-std=c23` build
gcc-15 switched to -std=c23 by default:

    https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212

Without the change the build fails as:

    ../src/clients/lib/xmmsclient/service/client.c:350:51: error: incompatible types when returning type ‘_Bool’ but ‘xmmsc_sc_namespace_t *’ {aka ‘struct xmmsc_sc_namespace_St *’} was expected
      350 |         x_api_error_if (!name, "with NULL name.", false);
          |                                                   ^~~~~