src/clients/lib/xmmsclient/visualization/unixshm.c: fix `-std=c23` build
gcc-15 switched to -std=c23 by default:

    https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212

Without the change the build fails as:

    ../src/clients/lib/xmmsclient/visualization/unixshm.c:31:24: error: incompatible types when returning type ‘_Bool’ but ‘xmmsc_result_t *’ {aka ‘struct xmmsc_result_St *’} was expected
       31 |                 return false;
          |                        ^~~~~